version: '3.8'
services:
  frontend-prod:
    image: navigator-front-prod
    build: ./navigator-front/.
    restart: always
    platform: linux/amd64
    ports:
      - "3001:80"
    command: ["serve", "-s", "build", "-l", "80"]
